services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password123
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-server
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password123
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    command: start-dev
    networks:
      - keycloak-network

  app-postgres:
    image: postgres:15
    container_name: app-postgres
    environment:
      POSTGRES_DB: whiteboardapp
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass123
    ports:
      - "5432:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  ml-service:  # Service name can be anything; it doesn't need to match folder
    build: 
      context: ./image_classification  # Points to your renamed folder
      dockerfile: Dockerfile
    container_name: ml-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network
    restart: unless-stopped

volumes:
  keycloak_db_data:
  app_db_data:

networks:
  keycloak-network:
  app-network:
