services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password123
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-server
    volumes:
      - ./WhiteboardApp-realm.json:/opt/keycloak/data/import/realm.json
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    command:
      - start-dev
      - --http-relative-path=/auth
      - --import-realm
    networks:
      - keycloak-network

  app-postgres:
    image: postgres:15
    container_name: app-postgres
    environment:
      POSTGRES_DB: whiteboardapp
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass123
    ports:
      - "5432:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  ml-service:
    build:
      context: ./image_classification
      dockerfile: Dockerfile
    container_name: ml-service
    environment:
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  keycloak_db_data:
  app_db_data:

networks:
  keycloak-network:
  app-network:
